---
hostname: millau

ssh_public_key: "{{ vault_ssh_public_key }}"
ssh_private_key: "{{ vault_ssh_private_key }}"

ansible_user: root

admin_user: lhapaipai
admin_password: "{{ vault_admin_password }}"


distrib_codename: jammy

server_hostname: millau.pentatrion.com

arch: amd64

