---
- name: "root | .bashrc"
  ansible.builtin.copy:
    src: root.bashrc
    dest: "/root/.bashrc"

- name: "root | .inputrc"
  ansible.builtin.copy:
    src: .inputrc
    dest: "/root/.inputrc"

- name: "{{ admin_user }} | .bashrc"
  ansible.builtin.copy:
    src: user.bashrc
    dest: "/home/{{ admin_user }}/.bashrc"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"

- name: "{{ admin_user }} | .inputrc"
  ansible.builtin.copy:
    src: .inputrc
    dest: "/home/{{ admin_user }}/.inputrc"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"

- name: "{{ admin_user }} | .gitconfig"
  ansible.builtin.copy:
    src: .gitconfig
    dest: "/home/{{ admin_user }}/.gitconfig"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
