services:
  whoami:
    labels:
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
  front:
    build:
      context: ./packages/front/docker
      additional_contexts:
        workspace: .
    environment:
      DATABASE_URL: postgresql://user:secret@db:5432/app?schema=public
    ports:
      - 3000:3000
    labels:
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.rule=Host(`front.docker.localhost`)"

  db:
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: app
      POSTGRES_PASSWORD: secret

    ports:
      - 5441:5432
