global:
  sendAnonymousUsage: false

api:
  dashboard: true
  
providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yaml

entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: ":443"

