---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Policy
  # https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items:
    - {direction: incoming, policy: deny}
    - {direction: outgoing, policy: allow}

# - name: SSH port
#   community.general.ufw:
#     rule: limit
#     port: ssh

- name: http
  # https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html
  # https://coolify.io/docs/knowledge-base/server/firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - http
    - https
    - ssh
    - "8080"

- name: Activation
  community.general.ufw:
    state: enabled
