services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:v3.3
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - net-rr
networks:
  net-rr:
    external: true
