services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs/:/etc/certs:ro
    networks:
      - net-rr
networks:
  # net-exposed: ~
  net-rr:
    external: true
